### ISSUE TITLE
[PROJECT] Dashboard Navbar

### ISSUE THREAD

**Issue by MintzyG** [MintzyG/SCTI#136]
# Organizar a navbar na dashboard
## Código atual:
```html
    {{ if not .IsVerified }}
      <div id="email-verification">
        <button hx-post="/send-verification-email"
                hx-trigger="click"
                hx-target="#email_message"
                hx-swap="innerHTML"
                hx-indicator="#loading-indicator"
                hx-refresh="true">
          Verificar Email
        </button>
        <div id="loading-indicator" class="htmx-indicator">
          <!-- SVG spinner code here -->
        </div>
        <div id="email_message"></div>
      </div>
    {{ end }}

    <nav class="header-nav">
      <h2 class="nav-title-pixel">Painel do Usuário</h2>
      <a href="/ingresso" class="pink-pixel-button">
        <img src="/static/assets/home/button.svg" />
        <p>Comprar</p>
      </a>
      <a href="/logoff" class="pink-pixel-button">
        <img src="/static/assets/home/button.svg" />
        <p>Logoff</p>
      </a>
    </nav>
```
## Visual Atual
![image](https://github.com/user-attachments/assets/67f31b7c-3ea3-461a-87c3-20299e4d4d3f)

## Problemas:

Botão de Verificar email não estilizado
Titulo da Nav bar na mesma linha dos botoes

## Solução proposta:

Seria ideal se o titulo estivesse em cima dos botões.
O botao de verificar email fosse incluso na nav bar, e os três botões centralizados

**Comment by juanzeen** [comment]
Se o título ficar em cima dos botões acho que vai quebrar a ideia de navbar, porque normalmente ela fica como o elemento no topo da página. Minha sugestão seria colocar o verify email junto na navbar e deixar o painel de usuário como título principal

**Comment by MintzyG** [comment]
certo, mas então acho melhor não deixar tudo igualmente espaçado, está super estranho assim na minha opinião

**Comment by juanzeen** [comment]
o verificar email acabou ficando fora do container das navs, aí realmente fica meio zoadinho. Colocando ele dentro do container esse layout já fica bem mais legal. Dá pra fazer o teste de duas formas, ou mantém a ideia de navbar e o título embaixo ou deixa o título como primeiro elemento e muda a ideia dos botões pra um container menor centralizado

**Comment by MintzyG** [comment]
Acho justo fazer as duas e deixar o pessoal fazer um voto no que fica mais visualmente melhor

**Comment by juanzeen** [comment]
![image](https://github.com/user-attachments/assets/1472442c-623b-4cb7-9c30-7053001d0af0)


Quer que teste colocando os elementos centralizados?

**Comment by MintzyG** [comment]
Acho que assim fica bom, só eu que acho meio estranho os botoes da nav bar muito separados assim.
Na minha opiniao eles mais juntinhos na direita faz mais sentido. Se não pra mim como user parece que esqueceram o botao ali no meio perdido. Se é que isso faz sentido pra você mas assim ta bom

**Comment by juanzeen** [comment]
Fiz aqui, vou mostrar resultados no PR
