### ISSUE TITLE
[DOCS] Verificar erros na escrita

### ISSUE THREAD

**Issue by BMSales** [MintzyG/SCTI#8]
**Você quer adicionar ou mudar documentação**
- [ ] Criar
- [ ] Adicionar
- [ ] Mudar
- [x] Corrigir

**Motivo da Issue**
Verificar erros na escrita da documentação projeto.

**Finalidade**
Melhorar a legibilidade da documentação do projeto.

**Comment by MintzyG** [comment]
#17 works towards this issue
